export const TmmRecords = {
    EAN: "ISBN",
    EBOOK_ISBN:"eBook ISBN",
    FULL_TITLE:'TITLE',
    TITLEPREFIXANDTITLE:"Title Prefix",
    SUBTITLE:"Subtitle",
    SERIES_NAME:"Series",
    US_PRICE:"US_PRICE",
    CANADIAN_PRICE:"Canadian Price",
    UK_PRICE:"UK Price",
    AUTHOR_1:"Author",
    TESTIMPRINTFROMHNA:"Imprint",
    FORMAT:"Format",
    BISAC1_DESC:"BISAC Description",
    SEASON:"Season",
    BISAC_STATUS:"Bisac Status",
    ORIGIN:"Origin",
    EDITOR:"Editor",
    MANAGING_EDITOR:"Managaing Editor",
    PARENT_ISBN:"Parent ISBN",
    PUB_DATE:"Pub Date",
    WAREHOUSE_DATE:"Warehouse Date",
    RELEASE_DATE:"Release Date",
    GROUP_1:"Division",
    LICENSED:"Licensed",
    LICENSOR:"Licensor"
  };